version: 0.2

phases:
  install:
    runtime-versions:
        java: openjdk11
  build:
    commands:
      - mvn clean
      - mvn install
artifacts:
  files:
    - 'Dockerfile'
    - 'target/example-1.0.0-SNAPSHOT.jar'
