version: 0.2

phases:
  install:
    runtime-versions:
        java: openjdk11
  build:
    commands:
      - mvn clean
      - mvn install
artifacts:
  files:
    - 'Dockerfile'
    - './target/example-0.0.1-SNAPSHOT.jar'
